remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Override Homepage"
description: "A Chrome Extension that lets you override the default homepage."
show_downloads: "false"
